version: '3.3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      XDEBUG_CONFIG: client_host=host.docker.internal

    volumes:
      - ./wordpress:/var/www/html/
      - ./wp-content:/var/www/html/wp-content/
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    depends_on:
      - db

  wp-cli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html/
      - ./wp-content:/var/www/html/wp-content/
    depends_on:
      - db
      - wordpress
    entrypoint: wp
    command: --info
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}